<?php

namespace App\Domain\Audit;

class AuditEventKeys
{
    public const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';

    public const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';

    public const AUTH_LOGIN_INACTIVE = 'AUTH_LOGIN_INACTIVE';

    public const AUTH_LOGOUT = 'AUTH_LOGOUT';

    public const ORDER_CREATED = 'ORDER_CREATED';

    public const PAYMENT_ADDED = 'PAYMENT_ADDED';

    public const ORDER_LAUNDRY_STATUS_UPDATED = 'ORDER_LAUNDRY_STATUS_UPDATED';

    public const ORDER_COURIER_STATUS_UPDATED = 'ORDER_COURIER_STATUS_UPDATED';

    public const ORDER_COURIER_ASSIGNED = 'ORDER_COURIER_ASSIGNED';

    public const ORDER_SCHEDULE_UPDATED = 'ORDER_SCHEDULE_UPDATED';

    public const ORDER_COLLECTION_UPDATED = 'ORDER_COLLECTION_UPDATED';

    public const WA_PROVIDER_CONFIG_UPDATED = 'WA_PROVIDER_CONFIG_UPDATED';

    public const WA_TEMPLATE_UPDATED = 'WA_TEMPLATE_UPDATED';

    public const CUSTOMER_ARCHIVED = 'CUSTOMER_ARCHIVED';

    public const CUSTOMER_RESTORED = 'CUSTOMER_RESTORED';

    public const SERVICE_ARCHIVED = 'SERVICE_ARCHIVED';

    public const SERVICE_RESTORED = 'SERVICE_RESTORED';

    public const OUTLET_SERVICE_OVERRIDE_UPSERTED = 'OUTLET_SERVICE_OVERRIDE_UPSERTED';

    public const OUTLET_SERVICE_OVERRIDE_UPDATED = 'OUTLET_SERVICE_OVERRIDE_UPDATED';

    public const OUTLET_ARCHIVED = 'OUTLET_ARCHIVED';

    public const OUTLET_RESTORED = 'OUTLET_RESTORED';

    public const SHIPPING_ZONE_CREATED = 'SHIPPING_ZONE_CREATED';

    public const SHIPPING_ZONE_UPDATED = 'SHIPPING_ZONE_UPDATED';

    public const SHIPPING_ZONE_DEACTIVATED = 'SHIPPING_ZONE_DEACTIVATED';

    public const SHIPPING_ZONE_ACTIVATED = 'SHIPPING_ZONE_ACTIVATED';

    public const USER_ARCHIVED = 'USER_ARCHIVED';

    public const USER_RESTORED = 'USER_RESTORED';

    public const USER_INVITED = 'USER_INVITED';

    public const USER_ASSIGNMENT_UPDATED = 'USER_ASSIGNMENT_UPDATED';
}
